interface ProjectConfig {
  namespace: string
  packFormat: number
  description: string
}

let config: ProjectConfig = {
  namespace: 'my_datapack',
  packFormat: 26,
  description: 'Generated by Datapack Builder'
}

export function setProjectConfig(partial: Partial<ProjectConfig>): void {
  config = { ...config, ...partial }
}

export function getProjectConfig(): ProjectConfig {
  return config
}