interface ProjectConfig {
  namespace: string
  packFormat: number
  description: string
  noNameMangling: boolean
}

let config: ProjectConfig = {
  namespace: 'my_datapack',
  packFormat: 26,
  description: 'Generated by Datapack Builder',
  noNameMangling: true  // true for dev, usually false
}

export function setProjectConfig(partial: Partial<ProjectConfig>): void {
  config = { ...config, ...partial }
}

export function getProjectConfig(): ProjectConfig {
  return config
}

export function getInternalNamespace(): string {
  return config.noNameMangling ? 'dpb_internal' : `__dpb_${config.namespace}_internal`
}