import { create } from 'zustand'

export interface ProjectConfig {
  namespace: string
  packFormat: number
  description: string
  noNameMangling: boolean
}

interface ProjectConfigStore {
  projectConfig: ProjectConfig
  updateConfig: (partial: Partial<ProjectConfig>) => void
}

export const useProjectConfigStore = create<ProjectConfigStore>((set) => ({
  projectConfig: {
    namespace: 'my_datapack',
    packFormat: 26,
    description: 'Generated by Datapack Builder',
    noNameMangling: false,
  },
  updateConfig: (partial) =>
    set((state) => ({ projectConfig: { ...state.projectConfig, ...partial } })),
}))