import { create } from 'zustand'

export interface ProjectConfig {
  namespace: string
  packFormat: number
  description: string
  noNameMangling: boolean
}

interface ProjectConfigStore {
  projectConfig: ProjectConfig
  updateConfig: (partial: Partial<ProjectConfig>) => void
  replaceConfig: (config: ProjectConfig) => void
}

export const DEFAULT_CONFIG: ProjectConfig = {
  namespace: 'my_datapack',
  packFormat: 26,
  description: 'Generated by Datapack Builder',
  noNameMangling: false,
}

export const useProjectConfigStore = create<ProjectConfigStore>((set) => ({
  projectConfig: DEFAULT_CONFIG,
  updateConfig: (partial) =>
    set((state) => ({ projectConfig: { ...state.projectConfig, ...partial } })),
  replaceConfig: (config) =>
    set({ projectConfig: config }),
}))